checks:
  php:
    custom_coding_standard:
      git_repository: 'https://github.com/cakephp/cakephp-codesniffer'
      ruleset_path: 'CakePHP/ruleset.xml'

filter:
  paths:
    - 'config/*'
    - 'src/*'
    - 'webroot/*'
  dependency_paths:
    - 'vendors/*'
    - 'webroot/js/jquery.min.js'
    - 'webroot/js/jquery.jsonview.js'

build:
  image: default-jammy
  environment:
    node: v22
  nodes:
    analysis:
      environment:
        php:
          version: 8.3.3
      tests:
        override:
          - php-scrutinizer-run
