language: php

dist: bionic
sudo: false

php:
  - 7.2
  - 7.3
  - 7.4

cache:
  directories:
    - vendor
    - $HOME/.composer/cache

jobs:
  fast_finish: true

  include:
    - php: 7.2
      env: "RUN=phpcs"
      before_script: skip
      script: |
        vendor/bin/phpcs -n -p --extensions=php \
          --standard=vendor/cakephp/cakephp-codesniffer/CakePHP \
          ./config ./src ./tests
      after_success: ~

    - php: 7.2
      env: "RUN=phpstan"
      install:
        - composer install --prefer-dist --no-interaction
        - composer require --dev phpstan/phpstan
      before_script: skip
      script: vendor/bin/phpstan analyse --no-progress src
      after_success: ~

  allow_failures:
    - env: "RUN=phpstan"

before_install:
  # Use GitHub OAuth token with Composer to increase API limits.
  - if [ -n "$GH_TOKEN" ]; then composer config github-oauth.github.com ${GH_TOKEN}; fi

install:
  # Install Composer dependencies.
  - composer install --prefer-dist --no-interaction

before_script:
  - phpenv rehash
  - set +H

script: vendor/bin/phpunit # Run PHPUnit.

after_success: bash <(curl -s https://codecov.io/bash) # Upload test coverage reports to CodeCov.

notifications:
  email: false
