language: php

php:
  - 5.5
  - 5.6
  - 7.0
  - hhvm

sudo: false

cache:
  directories:
    - vendor
    - $HOME/.composer/cache

env:
  global:
    - RUN_TESTS=1

matrix:
  fast_finish: true

  include:
    - php: 7.0
      env: RUN_CS=1 RUN_TESTS=0

  allow_failures:
    - php: hhvm

before_script:
  - if [ -n "$GH_TOKEN" ]; then composer config github-oauth.github.com ${GH_TOKEN}; fi;
  - composer install --prefer-dist --no-interaction

  - if [ "$TRAVIS_PHP_VERSION" = 'hhvm' ]; then composer require lorenzo/multiple-iterator=~1.0; fi

script:
  - if [ "$RUN_TESTS" = '1' ]; then vendor/bin/phpunit --coverage-clover=clover.xml; fi
  - if [ "$RUN_CS" = '1' ]; then vendor/bin/phpcs -n -p --extensions=php --standard=vendor/cakephp/cakephp-codesniffer/CakePHP ./src ./tests; fi

after_success:
  - if [ "$RUN_TESTS" = '1' ]; then bash <(curl -s https://codecov.io/bash); fi

notifications:
  email: false
